class_name IconPaths
extends RefCounted

const ICON_MAP: Dictionary = {
	# 初期5はキャラ名ファイル。adventurer_id 優先、職キーは互換エイリアス。
	"chr:adventurer_0":            "res://assets/ui/chr_icons/ICO_CHR_Ald.png",
	"chr:adventurer_1":            "res://assets/ui/chr_icons/ICO_CHR_Riva.png",
	"chr:adventurer_2":            "res://assets/ui/chr_icons/ICO_CHR_Elias.png",
	"chr:adventurer_3":            "res://assets/ui/chr_icons/ICO_CHR_Garen.png",
	"chr:adventurer_4":            "res://assets/ui/chr_icons/ICO_CHR_Mirei.png",
	"chr:swordsman":               "res://assets/ui/chr_icons/ICO_CHR_Ald.png",
	"chr:ranger":                  "res://assets/ui/chr_icons/ICO_CHR_Riva.png",
	"chr:alchemist":               "res://assets/ui/chr_icons/ICO_CHR_Elias.png",
	"chr:vanguard":                "res://assets/ui/chr_icons/ICO_CHR_Garen.png",
	"chr:beast_tamer":             "res://assets/ui/chr_icons/ICO_CHR_Mirei.png",
	"chr:pet_jack":                "res://assets/ui/chr_icons/ICO_CHR_Jack.png",
	"weapon:iron_sword":           "res://assets/ui/equipment/ICO_WPN_IronSword.png",
	"weapon:rusted_blade":         "res://assets/ui/equipment/ICO_WPN_RustedBlade.png",
	"weapon:heater_blade":         "res://assets/ui/equipment/ICO_WPN_HeaterBlade.png",
	"weapon:frost_blade":          "res://assets/ui/equipment/ICO_WPN_FrostBlade.png",
	"weapon:bolt_knife":           "res://assets/ui/equipment/ICO_WPN_BoltKnife.png",
	"weapon:apprentice_staff":     "res://assets/ui/equipment/ICO_WPN_ApprenticeStaff.png",
	"weapon:hunting_bow":          "res://assets/ui/equipment/ICO_WPN_HuntingBow.png",
	"weapon:sanctified_dagger":    "res://assets/ui/equipment/ICO_WPN_SanctifiedDagger.png",
	"weapon:ember_fang":           "res://assets/ui/equipment/ICO_WPN_EmberFang.png",
	"weapon:glacier_staff":        "res://assets/ui/equipment/ICO_WPN_GlacierStaff.png",
	"weapon:storm_edge":           "res://assets/ui/equipment/ICO_WPN_StormEdge.png",
	"weapon:umbral_fang":          "res://assets/ui/equipment/ICO_WPN_UmbralFang.png",
	"weapon:consecrated_maul":     "res://assets/ui/equipment/ICO_WPN_ConsecratedMaul.png",
	"weapon:burial_crown_greatsword": "res://assets/ui/equipment/ICO_WPN_BurialCrownGreatsword.png",
	"weapon:stormveil_needle":     "res://assets/ui/equipment/ICO_WPN_StormveilNeedle.png",
	"weapon:noctumbra_fang":       "res://assets/ui/equipment/ICO_WPN_NoctumbraFang.png",
	"weapon:mistpierce_halberd":   "res://assets/ui/equipment/ICO_WPN_MistpierceHalberd.png",
	"weapon:eldion_spine":         "res://assets/ui/equipment/ICO_WPN_EldionSpine.png",
	"weapon:pharos_flare":         "res://assets/ui/equipment/ICO_WPN_PharosFlare.png",
	"weapon:shadowcord":           "res://assets/ui/equipment/ICO_WPN_Shadowcord.png",
	"weapon:silvaria_fang":        "res://assets/ui/equipment/ICO_WPN_SilvariaFang.png",
	"weapon:eldion_claw":          "res://assets/ui/equipment/ICO_WPN_EldionClaw.png",
	"weapon:unidentified":         "res://assets/ui/batch2/ICO_WPN_Unidentified.png",
	# ② ウィスパーウッド — 専用 icon 9点（★2+代表7）。残11点は placeholder（P3-D154）
	"weapon:verdant_cleaver":      "res://assets/ui/equipment/ICO_WPN_VerdantCleaver.png",
	"weapon:bark_render":          "res://assets/ui/equipment/ICO_WPN_BarkRender.png",
	"weapon:verdia_longbow":       "res://assets/ui/equipment/ICO_WPN_VerdiaLongbow.png",
	"weapon:moss_staff":           "res://assets/ui/equipment/ICO_WPN_MossStaff.png",
	"weapon:pyre_greatsword":      "res://assets/ui/equipment/ICO_WPN_PyreGreatsword.png",
	"weapon:tinder_bow":           "res://assets/ui/equipment/ICO_WPN_TinderBow.png",
	"weapon:willow_ember_staff":   "res://assets/ui/equipment/ICO_WPN_WillowEmberStaff.png",
	"weapon:venom_fang_blades":    "res://assets/ui/equipment/ICO_WPN_VenomFangBlades.png",
	"weapon:symbiont_edge":        "res://assets/ui/equipment/ICO_WPN_SymbiontEdge.png",
	"weapon:mist_piercer":         "res://assets/ui/equipment/ICO_WPN_MistPiercer.png",
	"weapon:silvaria_oathblade":   "res://assets/ui/equipment/ICO_WPN_SilvariaOathblade.png",
	"weapon:veld_branch_staff":    "res://assets/ui/equipment/ICO_WPN_VeldBranchStaff.png",
	# ③ ミストフェン — 専用 icon 9点（★2+代表7）。残11点は placeholder（P3-D156）
	"weapon:bog_cleaver":          "res://assets/ui/equipment/ICO_WPN_BogCleaver.png",
	"weapon:leech_fang_blades":    "res://assets/ui/equipment/ICO_WPN_LeechFangBlades.png",
	"weapon:mire_longbow":         "res://assets/ui/equipment/ICO_WPN_MireLongbow.png",
	"weapon:driftwood_staff":      "res://assets/ui/equipment/ICO_WPN_DriftwoodStaff.png",
	"weapon:storm_carver":         "res://assets/ui/equipment/ICO_WPN_StormCarver.png",
	"weapon:galvanic_bow":         "res://assets/ui/equipment/ICO_WPN_GalvanicBow.png",
	"weapon:fen_lantern_staff":    "res://assets/ui/equipment/ICO_WPN_FenLanternStaff.png",
	"weapon:carapace_saw":         "res://assets/ui/equipment/ICO_WPN_CarapaceSaw.png",
	"weapon:thunderfen_edge":      "res://assets/ui/equipment/ICO_WPN_ThunderfenEdge.png",
	"weapon:volt_needle":          "res://assets/ui/equipment/ICO_WPN_VoltNeedle.png",
	"weapon:volgrave_thunderblade": "res://assets/ui/equipment/ICO_WPN_VolgraveThunderblade.png",
	"weapon:seradion_storm_staff": "res://assets/ui/equipment/ICO_WPN_SeradionStormStaff.png",
	# ④ ブラックショア — 専用 icon 9点（★2+代表7）。残11点は placeholder（P3-D160）
	"weapon:black_sand_cleaver":   "res://assets/ui/equipment/ICO_WPN_BlackSandCleaver.png",
	"weapon:wreck_hook_blades":    "res://assets/ui/equipment/ICO_WPN_WreckHookBlades.png",
	"weapon:tidewood_longbow":     "res://assets/ui/equipment/ICO_WPN_TidewoodLongbow.png",
	"weapon:brine_lantern_staff":  "res://assets/ui/equipment/ICO_WPN_BrineLanternStaff.png",
	"weapon:lighthouse_greatsword": "res://assets/ui/equipment/ICO_WPN_LighthouseGreatsword.png",
	"weapon:pharos_bow":           "res://assets/ui/equipment/ICO_WPN_PharosBow.png",
	"weapon:votive_staff":         "res://assets/ui/equipment/ICO_WPN_VotiveStaff.png",
	"weapon:barnacle_saw":         "res://assets/ui/equipment/ICO_WPN_BarnacleSaw.png",
	"weapon:sanctum_tide_edge":    "res://assets/ui/equipment/ICO_WPN_SanctumTideEdge.png",
	"weapon:beacon_needle":        "res://assets/ui/equipment/ICO_WPN_BeaconNeedle.png",
	"weapon:nereidas_tideblade":   "res://assets/ui/equipment/ICO_WPN_NereidasTideblade.png",
	"weapon:pharoslight_staff":    "res://assets/ui/equipment/ICO_WPN_PharoslightStaff.png",
	# ⑤ フロストリッジ武器（暫定流用 / P3-BETA-004）
	"weapon:ridge_cleaver":        "res://assets/ui/equipment/ICO_WPN_RidgeCleaver.png",
	"weapon:frostclaw_blades":     "res://assets/ui/equipment/ICO_WPN_FrostclawBlades.png",
	"weapon:snowline_longbow":     "res://assets/ui/equipment/ICO_WPN_SnowlineLongbow.png",
	"weapon:cairn_staff":          "res://assets/ui/equipment/ICO_WPN_CairnStaff.png",
	"weapon:glacier_greatsword":   "res://assets/ui/equipment/ICO_WPN_GlacierGreatsword.png",
	"weapon:rime_bow":             "res://assets/ui/equipment/ICO_WPN_RimeBow.png",
	"weapon:aurora_staff":         "res://assets/ui/equipment/ICO_WPN_AuroraStaff.png",
	"weapon:shadow_fang_saw":      "res://assets/ui/equipment/ICO_WPN_ShadowFangSaw.png",
	"weapon:permafrost_edge":      "res://assets/ui/equipment/ICO_WPN_PermafrostEdge.png",
	"weapon:white_needle":         "res://assets/ui/equipment/ICO_WPN_WhiteNeedle.png",
	"weapon:eldion_frostbrand":    "res://assets/ui/equipment/ICO_WPN_EldionFrostbrand.png",
	"weapon:umbra_terminus_staff": "res://assets/ui/equipment/ICO_WPN_UmbraTerminusStaff.png",
	"armor:leather_armor":         "res://assets/ui/equipment/ICO_ARM_LeatherArmor.png",
	"armor:bone_armor":            "res://assets/ui/equipment/ICO_ARM_BoneArmor.png",
	"armor:rune_linen_garb":       "res://assets/ui/equipment/ICO_ARM_RuneLinenGarb.png",
	"armor:crystal_vest":          "res://assets/ui/equipment/ICO_ARM_CrystalVest.png",
	"armor:mourngate_plate":       "res://assets/ui/equipment/ICO_ARM_MourngatePlate.png",
	"armor:serdion_ward_plate":    "res://assets/ui/equipment/ICO_ARM_SerdionWardPlate.png",
	"armor:immortal_cenotaph_plate": "res://assets/ui/equipment/ICO_ARM_ImmortalCenotaphPlate.png",
	"armor:granvel_bark_plate":    "res://assets/ui/equipment/ICO_ARM_GranvelBarkPlate.png",
	"armor:moldgar_abyss_mail":    "res://assets/ui/equipment/ICO_ARM_MoldgarAbyssMail.png",
	"armor:nereion_tide_plate":    "res://assets/ui/equipment/ICO_ARM_NereionTidePlate.png",
	"armor:eldion_glacier_aegis":  "res://assets/ui/equipment/ICO_ARM_EldionGlacierAegis.png",
	# ② ウィスパーウッド防具（暫定流用 / P3-D154）
	"armor:moss_weave_garb":       "res://assets/ui/equipment/ICO_ARM_MossWeaveGarb.png",
	"armor:barkplate_mail":        "res://assets/ui/equipment/ICO_ARM_BarkplateMail.png",
	"armor:mycel_cloak":           "res://assets/ui/equipment/ICO_ARM_MycelCloak.png",
	"armor:wyvern_scale_plate":    "res://assets/ui/equipment/ICO_ARM_WyvernScalePlate.png",
	"armor:warden_vestment":       "res://assets/ui/equipment/ICO_ARM_WardenVestment.png",
	# ③ ミストフェン防具（暫定流用 / P3-BETA-002）
	"armor:mire_hide_garb":        "res://assets/ui/equipment/ICO_ARM_MireHideGarb.png",
	"armor:chitin_plate":          "res://assets/ui/equipment/ICO_ARM_ChitinPlate.png",
	"armor:bog_strider_cloak":     "res://assets/ui/equipment/ICO_ARM_BogStriderCloak.png",
	"armor:moldgar_scale_mail":    "res://assets/ui/equipment/ICO_ARM_MoldgarScaleMail.png",
	"armor:libris_ward_robe":      "res://assets/ui/equipment/ICO_ARM_LibrisWardRobe.png",
	# ④ ブラックショア防具（暫定流用 / P3-BETA-003）
	"armor:tidecloth_garb":        "res://assets/ui/equipment/ICO_ARM_TideclothGarb.png",
	"armor:shipplate_mail":        "res://assets/ui/equipment/ICO_ARM_ShipplateMail.png",
	"armor:kelp_weave_cloak":      "res://assets/ui/equipment/ICO_ARM_KelpWeaveCloak.png",
	"armor:whalebone_plate":       "res://assets/ui/equipment/ICO_ARM_WhalebonePlate.png",
	"armor:votive_vestment":       "res://assets/ui/equipment/ICO_ARM_VotiveVestment.png",
	# ⑤ フロストリッジ防具（暫定流用 / P3-BETA-004）
	"armor:furline_garb":          "res://assets/ui/equipment/ICO_ARM_FurlineGarb.png",
	"armor:glacier_plate":         "res://assets/ui/equipment/ICO_ARM_GlacierPlate.png",
	"armor:snowdrift_cloak":       "res://assets/ui/equipment/ICO_ARM_SnowdriftCloak.png",
	"armor:dragon_scale_aegis":    "res://assets/ui/equipment/ICO_ARM_DragonScaleAegis.png",
	"armor:aurora_vestment":       "res://assets/ui/equipment/ICO_ARM_AuroraVestment.png",
	"armor:crypt_weave_cloak":           "res://assets/ui/equipment/ICO_ARM_CryptWeaveCloak.png",
	"armor:lament_guard_mail":           "res://assets/ui/equipment/ICO_ARM_LamentGuardMail.png",
	"armor:sepia_hide_vest":           "res://assets/ui/equipment/ICO_ARM_SepiaHideVest.png",
	"armor:unidentified":          "res://assets/ui/batch2/ICO_ARM_Unidentified.png",
	"accessory:silver_ring":       "res://assets/ui/equipment/ICO_ACC_SilverRing.png",
	"accessory:mourngate_sigil":   "res://assets/ui/equipment/ICO_ACC_MourngateSigil.png",
	"accessory:mourngate_royal_seal": "res://assets/ui/equipment/ICO_ACC_MourngateRoyalSeal.png",
	"accessory:council_hegemony_seal": "res://assets/ui/equipment/ICO_ACC_CouncilHegemonySeal.png",
	"accessory:silvaria_covenant_ring": "res://assets/ui/equipment/ICO_ACC_SilvariaCovenantRing.png",
	"accessory:seradis_archive_seal": "res://assets/ui/equipment/ICO_ACC_SeradisArchiveSeal.png",
	"accessory:pharos_beacon_ring": "res://assets/ui/equipment/ICO_ACC_PharosBeaconRing.png",
	"accessory:frostridge_boundary_signet": "res://assets/ui/equipment/ICO_ACC_FrostridgeBoundarySignet.png",
	"accessory:relic_shard_charm": "res://assets/ui/equipment/ICO_ACC_RelicShardCharm.png",
	# ② ウィスパーウッド装飾品（暫定流用 / P3-D154）
	"accessory:verdant_ring":      "res://assets/ui/equipment/ICO_ACC_VerdantRing.png",
	"accessory:spore_charm":       "res://assets/ui/equipment/ICO_ACC_SporeCharm.png",
	"accessory:granvel_fang_talisman": "res://assets/ui/equipment/ICO_ACC_GranvelFangTalisman.png",
	# ③ ミストフェン装飾品（暫定流用 / P3-BETA-002）
	"accessory:marsh_pearl_ring":  "res://assets/ui/equipment/ICO_ACC_MarshPearlRing.png",
	"accessory:leech_oil_charm":   "res://assets/ui/equipment/ICO_ACC_LeechOilCharm.png",
	"accessory:moldgar_eye_talisman": "res://assets/ui/equipment/ICO_ACC_MoldgarEyeTalisman.png",
	# ④ ブラックショア装飾品（暫定流用 / P3-BETA-003）
	"accessory:black_pearl_ring":  "res://assets/ui/equipment/ICO_ACC_BlackPearlRing.png",
	"accessory:barnacle_charm":    "res://assets/ui/equipment/ICO_ACC_BarnacleCharm.png",
	"accessory:nereion_song_talisman": "res://assets/ui/equipment/ICO_ACC_NereionSongTalisman.png",
	# ⑤ フロストリッジ装飾品（暫定流用 / P3-BETA-004）
	"accessory:ice_crystal_ring":  "res://assets/ui/equipment/ICO_ACC_IceCrystalRing.png",
	"accessory:frost_fang_charm":  "res://assets/ui/equipment/ICO_ACC_FrostFangCharm.png",
	"accessory:eldion_heart_talisman": "res://assets/ui/equipment/ICO_ACC_EldionHeartTalisman.png",
	"accessory:clockwing_brooch":           "res://assets/ui/equipment/ICO_ACC_ClockwingBrooch.png",
	"accessory:pilgrim_lantern_charm":           "res://assets/ui/equipment/ICO_ACC_PilgrimLanternCharm.png",
	"accessory:unidentified":      "res://assets/ui/batch2/ICO_ACC_Unidentified.png",
	"material:relic_shard":        "res://assets/ui/materials/ICO_MAT_RelicShard.png",
	"material:base_ore":           "res://assets/ui/materials/ICO_MAT_BaseOre.png",
	"material:epic_ore":           "res://assets/ui/materials/ICO_MAT_EliteRelicShard.png",
	"material:elite_relic_shard":  "res://assets/ui/materials/ICO_MAT_EliteRelicShard.png",
	"material:ancient_bone":       "res://assets/ui/materials/ICO_MAT_AncientBone.png",
	"enemy:sepia_hound":           "res://assets/codex/enemies/ART_ENM_SepiaHound.png",
	"enemy:rune_roach":            "res://assets/codex/enemies/ART_ENM_RuneRoach.png",
	"enemy:crystal_hedgehog":      "res://assets/codex/enemies/ART_ENM_CrystalHedgehog.png",
	"enemy:crown_eater_rat":       "res://assets/codex/enemies/ART_ENM_CrownEaterRat.png",
	"enemy:grave_bell_bat":        "res://assets/codex/enemies/ART_ENM_GraveBellBat.png",
	"enemy:crystal_scorpion":      "res://assets/codex/enemies/ART_ENM_CrystalScorpion.png",
	"enemy:skullface_mantis":      "res://assets/codex/enemies/ART_ENM_SkullfaceMantis.png",
	"enemy:clock_moth":            "res://assets/codex/enemies/ART_ENM_ClockMoth.png",
	"enemy:cosmic_duck": "res://assets/codex/enemies/ART_ENM_CosmicDuck.png",
	"enemy:crown_raven": "res://assets/codex/enemies/ART_ENM_CrownRaven.png",
	"enemy:golden_scarab": "res://assets/codex/enemies/ART_ENM_GoldenScarab.png",
	"enemy:shadow_stalker": "res://assets/codex/enemies/ART_ENM_ShadowStalker.png",
	"enemy:wayfarer_sparrow":      "res://assets/codex/enemies/ART_ENM_ClockMoth.png",
	"enemy:reliquary_beetle":      "res://assets/codex/enemies/ART_ENM_RuneRoach.png",
	"enemy:serdion":               "res://assets/codex/enemies/ART_BOSS_Serdion.png",
	# 戦闘行動順専用（枠焼込）。図鑑 `enemy:` は変更しない。
	"enemy_turn:sepia_hound":      "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_SepiaHound.png",
	"enemy_turn:rune_roach":       "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_RuneRoach.png",
	"enemy_turn:crystal_hedgehog": "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_CrystalHedgehog.png",
	"enemy_turn:crown_eater_rat":  "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_CrownEaterRat.png",
	"enemy_turn:grave_bell_bat":   "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_GraveBellBat.png",
	"enemy_turn:crystal_scorpion": "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_CrystalScorpion.png",
	"enemy_turn:skullface_mantis": "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_SkullfaceMantis.png",
	"enemy_turn:clock_moth":       "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_ClockMoth.png",
	"enemy_turn:cosmic_duck":      "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_CosmicDuck.png",
	"enemy_turn:crown_raven":      "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_CrownRaven.png",
	"enemy_turn:golden_scarab": "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_GoldenScarab.png",
	"enemy_turn:shadow_stalker": "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_ShadowStalker.png",
	"enemy_turn:serdion":          "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_Serdion.png",
	# ② ウィスパーウッド
	"enemy:iron_horn": "res://assets/codex/enemies/ART_ENM_IronHorn.png",
	"enemy:blood_bloom": "res://assets/codex/enemies/ART_ENM_BloodBloom.png",
	"enemy:rune_carcinos": "res://assets/codex/enemies/ART_ENM_RuneCarcinos.png",
	"enemy:mirror_boa": "res://assets/codex/enemies/ART_ENM_MirrorBoa.png",
	"enemy:moss_boar": "res://assets/codex/enemies/ART_ENM_MossBoar.png",
	"enemy:moss_shell": "res://assets/codex/enemies/ART_ENM_MossShell.png",
	"enemy:bloom_serpent":         "res://assets/codex/enemies/ART_ENM_BloomSerpent.png",
	"enemy:spore_widow": "res://assets/codex/enemies/ART_ENM_SporeWidow.png",
	"enemy:mist_wyvern": "res://assets/codex/enemies/ART_ENM_MistWyvern.png",
	"enemy:granvel": "res://assets/codex/enemies/ART_BOSS_Granvel.png",
	"enemy_turn:moss_boar": "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_MossBoar.png",
	"enemy_turn:moss_shell": "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_MossShell.png",
	"enemy_turn:spore_widow": "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_SporeWidow.png",
	"enemy_turn:iron_horn": "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_IronHorn.png",
	"enemy_turn:blood_bloom": "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_BloodBloom.png",
	"enemy_turn:rune_carcinos": "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_RuneCarcinos.png",
	"enemy_turn:mist_wyvern": "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_MistWyvern.png",
	"enemy_turn:mirror_boa": "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_MirrorBoa.png",
	"enemy_turn:granvel": "res://assets/ui/combat/enemy_icons/ICO_ENM_Turn_Granvel.png",
	# ③ ミストフェン
	"enemy:blood_leech":           "res://assets/codex/enemies/ART_ENM_BloodLeech.png",
	"enemy:dead_poison_frog":      "res://assets/codex/enemies/ART_ENM_DeadPoisonFrog.png",
	"enemy:mist_mantis":           "res://assets/codex/enemies/ART_ENM_MistMantis.png",
	"enemy:marsh_king":            "res://assets/codex/enemies/ART_ENM_MarshKing.png",
	"enemy:bone_picker":           "res://assets/codex/enemies/ART_ENM_GraveBellBat.png",
	"enemy:mire_strider_spider":   "res://assets/codex/enemies/ART_ENM_SporeWidow.png",
	"enemy:spore_needle_wasp":     "res://assets/codex/enemies/ART_ENM_MistMantis.png",
	"enemy:great_claw":            "res://assets/codex/enemies/ART_ENM_GreatClaw.png",
	"enemy:nightfen":              "res://assets/codex/enemies/ART_ENM_MarshKing.png",
	"enemy:moldgar":               "res://assets/codex/enemies/ART_BOSS_Moldgar.png",
	# ④ ブラックショア
	"enemy:ship_eater_crab":       "res://assets/codex/enemies/ART_ENM_ShipEaterCrab.png",
	"enemy:skull_turtle":          "res://assets/codex/enemies/ART_ENM_SkullTurtle.png",
	"enemy:undertaker_shark":      "res://assets/codex/enemies/ART_ENM_UndertakerShark.png",
	"enemy:samurai_fish":          "res://assets/codex/enemies/ART_ENM_SamuraiFish.png",
	"enemy:black_tide_shark":      "res://assets/codex/enemies/ART_ENM_UndertakerShark.png",
	"enemy:abyssal_squid":         "res://assets/codex/enemies/ART_ENM_NinjaOctopus.png",
	"enemy:tide_lamp":             "res://assets/codex/enemies/ART_ENM_MistWyvern.png",
	"enemy:ninja_octopus":         "res://assets/codex/enemies/ART_ENM_NinjaOctopus.png",
	"enemy:anchor_lord":           "res://assets/codex/enemies/ART_ENM_GreatClaw.png",
	"enemy:nereion":               "res://assets/codex/enemies/ART_BOSS_Nereion.png",
	# ⑤ フロストリッジ
	"enemy:frost_claw_raptor":     "res://assets/codex/enemies/ART_ENM_FrostClawRaptor.png",
	"enemy:vergaron":              "res://assets/codex/enemies/ART_ENM_Vergaron.png",
	"enemy:storm_joe":             "res://assets/codex/enemies/ART_ENM_StormJoe.png",
	"enemy:oldrex":                "res://assets/codex/enemies/ART_ENM_Oldrex.png",
	"enemy:ice_tail_fox":          "res://assets/codex/enemies/ART_ENM_Vergaron.png",
	"enemy:glacier_warden":        "res://assets/codex/enemies/ART_ENM_Oldrex.png",
	"enemy:wind_ripper":           "res://assets/codex/enemies/ART_ENM_Greios.png",
	"enemy:greios":                "res://assets/codex/enemies/ART_ENM_Greios.png",
	"enemy:polar_tricera":         "res://assets/codex/enemies/ART_ENM_StormJoe.png",
	"enemy:eldion":                "res://assets/codex/enemies/ART_BOSS_Eldion.png",
	"enemy:chronos_wave":          "res://assets/codex/enemies/ART_BOSS_Serdion.png",
	"enemy:valgard":               "res://assets/codex/enemies/ART_BOSS_Serdion.png",
	"enemy:skarpedion":            "res://assets/codex/enemies/ART_BOSS_Granvel.png",
	"enemy:mycolga_ancient":       "res://assets/codex/enemies/ART_BOSS_Moldgar.png",
	"enemy:karna_smoke":           "res://assets/codex/enemies/ART_BOSS_Moldgar.png",
	"enemy:nereion_depths":        "res://assets/codex/enemies/ART_BOSS_Nereion.png",
	"enemy:forgedormient":         "res://assets/codex/enemies/ART_BOSS_Eldion.png",
	"enemy:albark":                "res://assets/codex/enemies/ART_BOSS_Eldion.png",
	"dungeon:mourngate":           "res://assets/dungeon/mourngate/ICO_DG_Mourngate.png",
	"stage:mourngate_1_1":         "res://assets/dungeon/mourngate/stages/ICO_DG_Mourngate_1_1.png",
	"stage:mourngate_1_2":         "res://assets/dungeon/mourngate/stages/ICO_DG_Mourngate_1_2.png",
	"stage:mourngate_1_3":         "res://assets/dungeon/mourngate/stages/ICO_DG_Mourngate_1_3.png",
	"stage:mourngate_1_4":         "res://assets/dungeon/mourngate/stages/ICO_DG_Mourngate_1_4.png",
	"stage:mourngate_1_5":         "res://assets/dungeon/mourngate/stages/ICO_DG_Mourngate_1_5.png",
	# イベントDG章（暫定: ボス／代表敵アートから生成）
	"stage:cosmic_rift_1_1":       "res://assets/dungeon/event/stages/ICO_DG_CosmicRift_1_1.png",
	"stage:crown_rookery_1_1":     "res://assets/dungeon/event/stages/ICO_DG_CrownRookery_1_1.png",
	"stage:golden_nest_1_1":       "res://assets/dungeon/event/stages/ICO_DG_GoldenNest_1_1.png",
	"stage:shadow_hunt_1_1":       "res://assets/dungeon/event/stages/ICO_DG_ShadowHunt_1_1.png",
	"dungeon:cosmic_rift":         "res://assets/dungeon/event/stages/ICO_DG_CosmicRift_1_1.png",
	"dungeon:crown_rookery":       "res://assets/dungeon/event/stages/ICO_DG_CrownRookery_1_1.png",
	"dungeon:golden_nest":         "res://assets/dungeon/event/stages/ICO_DG_GoldenNest_1_1.png",
	"dungeon:shadow_hunt":         "res://assets/dungeon/event/stages/ICO_DG_ShadowHunt_1_1.png",
	# ② ウィスパーウッド — 章別 icon 5点（P3-DG-STG / WW-2）
	"stage:whisperwood_2_1":       "res://assets/dungeon/whisperwood/stages/ICO_DG_Whisperwood_2_1.png",
	"stage:whisperwood_2_2":       "res://assets/dungeon/whisperwood/stages/ICO_DG_Whisperwood_2_2.png",
	"stage:whisperwood_2_3":       "res://assets/dungeon/whisperwood/stages/ICO_DG_Whisperwood_2_3.png",
	"stage:whisperwood_2_4":       "res://assets/dungeon/whisperwood/stages/ICO_DG_Whisperwood_2_4.png",
	"stage:whisperwood_2_5":       "res://assets/dungeon/whisperwood/stages/ICO_DG_Whisperwood_2_5.png",
	# ③ ミストフェン — 章別 icon 5点（暫定: WW 流用・P3-DG-STG）
	"stage:mistfen_3_1":           "res://assets/dungeon/mistfen/stages/ICO_DG_Mistfen_3_1.png",
	"stage:mistfen_3_2":           "res://assets/dungeon/mistfen/stages/ICO_DG_Mistfen_3_2.png",
	"stage:mistfen_3_3":           "res://assets/dungeon/mistfen/stages/ICO_DG_Mistfen_3_3.png",
	"stage:mistfen_3_4":           "res://assets/dungeon/mistfen/stages/ICO_DG_Mistfen_3_4.png",
	"stage:mistfen_3_5":           "res://assets/dungeon/mistfen/stages/ICO_DG_Mistfen_3_5.png",
	# ④ ブラックショア — 章別 icon 5点（暫定: WW 流用）
	"stage:blackshore_4_1":        "res://assets/dungeon/blackshore/stages/ICO_DG_Blackshore_4_1.png",
	"stage:blackshore_4_2":        "res://assets/dungeon/blackshore/stages/ICO_DG_Blackshore_4_2.png",
	"stage:blackshore_4_3":        "res://assets/dungeon/blackshore/stages/ICO_DG_Blackshore_4_3.png",
	"stage:blackshore_4_4":        "res://assets/dungeon/blackshore/stages/ICO_DG_Blackshore_4_4.png",
	"stage:blackshore_4_5":        "res://assets/dungeon/blackshore/stages/ICO_DG_Blackshore_4_5.png",
	# ⑤ フロストリッジ — 章別 icon 5点（暫定: WW 流用）
	"stage:frostridge_5_1":        "res://assets/dungeon/frostridge/stages/ICO_DG_Frostridge_5_1.png",
	"stage:frostridge_5_2":        "res://assets/dungeon/frostridge/stages/ICO_DG_Frostridge_5_2.png",
	"stage:frostridge_5_3":        "res://assets/dungeon/frostridge/stages/ICO_DG_Frostridge_5_3.png",
	"stage:frostridge_5_4":        "res://assets/dungeon/frostridge/stages/ICO_DG_Frostridge_5_4.png",
	"stage:frostridge_5_5":        "res://assets/dungeon/frostridge/stages/ICO_DG_Frostridge_5_5.png",
	"dungeon:astoria_ruins":       "res://assets/dungeon/astoria_ruins/ICO_DG_AstoriaRuins.png",
	"dungeon:whisperwood":         "res://assets/dungeon/whisperwood/ICO_DG_Whisperwood.png",
	"dungeon:green_hollow":        "res://assets/dungeon/green_hollow/ICO_DG_GreenHollow.png",
	"dungeon:mistfen":             "res://assets/dungeon/mistfen/ICO_DG_Mistfen.png",
	"dungeon:broken_marsh":        "res://assets/dungeon/broken_marsh/ICO_DG_BrokenMarsh.png",
	"dungeon:blackshore":          "res://assets/dungeon/blackshore/ICO_DG_Blackshore.png",
	"dungeon:westbay_flats":       "res://assets/dungeon/westbay_flats/ICO_DG_WestbayFlats.png",
	"dungeon:frostridge":          "res://assets/dungeon/frostridge/ICO_DG_Frostridge.png",
	"dungeon:frostwall_path":      "res://assets/dungeon/frostwall_path/ICO_DG_FrostwallPath.png",
	"dungeon:mourngate_deep":      "res://assets/dungeon/mourngate/ICO_DG_Mourngate.png",
	"dungeon:storm_crown_ruins":   "res://assets/dungeon/astoria_ruins/ICO_DG_AstoriaRuins.png",
	"dungeon:red_ridge_mine":      "res://assets/dungeon/whisperwood/ICO_DG_Whisperwood.png",
	"dungeon:mistfen_depths":      "res://assets/dungeon/mistfen/ICO_DG_Mistfen.png",
	"dungeon:thunder_peak":        "res://assets/dungeon/broken_marsh/ICO_DG_BrokenMarsh.png",
	"dungeon:blackshore_abyss":    "res://assets/dungeon/blackshore/ICO_DG_Blackshore.png",
	"dungeon:red_forge_depths":    "res://assets/dungeon/frostridge/ICO_DG_Frostridge.png",
	"dungeon:north_reach":         "res://assets/dungeon/frostridge/ICO_DG_Frostridge.png",
	"relic:war_banner":             "res://assets/ui/relics/ICO_REL_WarBanner.png",
	"relic:aegis_shard":            "res://assets/ui/relics/ICO_REL_AegisShard.png",
	"relic:old_hourglass":          "res://assets/ui/relics/ICO_REL_OldHourglass.png",
	"relic:berserker_charm":        "res://assets/ui/relics/ICO_REL_BerserkerCharm.png",
	"relic:hunter_sigil":           "res://assets/ui/relics/ICO_REL_HunterSigil.png",
	"relic:reactive_aegis":         "res://assets/ui/relics/ICO_REL_ReactiveAegis.png",
	"relic:lament_ring":            "res://assets/ui/relics/ICO_REL_LamentRing.png",
	"relic:scout_lens":             "res://assets/ui/relics/ICO_REL_ScoutLens.png",
	# スキルアイコン（全量自動生成）
	"skill:aimed_shot":           "res://assets/ui/skills/ICO_SKILL_AimedShot.png",
	"skill:alpha_strike":           "res://assets/ui/skills/ICO_SKILL_AlphaStrike.png",
	"skill:apex_guard":           "res://assets/ui/skills/ICO_SKILL_ApexGuard.png",
	"skill:apex_hex":           "res://assets/ui/skills/ICO_SKILL_ApexHex.png",
	"skill:apex_shot":           "res://assets/ui/skills/ICO_SKILL_ApexShot.png",
	"skill:apex_slash":           "res://assets/ui/skills/ICO_SKILL_ApexSlash.png",
	"skill:apex_tame":           "res://assets/ui/skills/ICO_SKILL_ApexTame.png",
	"skill:arc_bolt":           "res://assets/ui/skills/ICO_SKILL_ArcBolt.png",
	"skill:armor_cleave":           "res://assets/ui/skills/ICO_SKILL_ArmorCleave.png",
	"skill:beast_bite":           "res://assets/ui/skills/ICO_SKILL_BeastBite.png",
	"skill:pet_bond_rally":           "res://assets/ui/skills/ICO_SKILL_TitanRoar.png",
	"skill:pet_command_fang":           "res://assets/ui/skills/ICO_SKILL_ApexTame.png",
	"skill:pet_bond_guard":           "res://assets/ui/skills/ICO_SKILL_ApexGuard.png",
	"skill:beast_dominion":           "res://assets/ui/skills/ICO_SKILL_BeastDominion.png",
	"skill:boss_decree_wave":           "res://assets/ui/skills/ICO_SKILL_BossDecreeWave.png",
	"skill:boss_enrage":           "res://assets/ui/skills/ICO_SKILL_BossEnrage.png",
	"skill:break_arrow":           "res://assets/ui/skills/ICO_SKILL_BreakArrow.png",
	"skill:break_stance":           "res://assets/ui/skills/ICO_SKILL_BreakStance.png",
	"skill:chain_slash":           "res://assets/ui/skills/ICO_SKILL_ChainSlash.png",
	"skill:curse_sigil":           "res://assets/ui/skills/ICO_SKILL_CurseSigil.png",
	"skill:dead_eye":           "res://assets/ui/skills/ICO_SKILL_DeadEye.png",
	"skill:empower":           "res://assets/ui/skills/ICO_SKILL_Empower.png",
	"skill:enemy_blizzard_howl":           "res://assets/ui/skills/ICO_SKILL_EnemyBlizzardHowl.png",
	"skill:enemy_bog_spray":           "res://assets/ui/skills/ICO_SKILL_EnemyBogSpray.png",
	"skill:enemy_chrono_resonance":           "res://assets/ui/skills/ICO_SKILL_EnemyChronoResonance.png",
	"skill:enemy_chronos_wave_gear_crush":    "res://assets/ui/skills/ICO_SKILL_EnemyChronoResonance.png",
	"skill:enemy_chronos_wave_resonance":     "res://assets/ui/skills/ICO_SKILL_EnemyChronoResonance.png",
	"skill:enemy_claw_guillotine":           "res://assets/ui/skills/ICO_SKILL_EnemyClawGuillotine.png",
	"skill:enemy_crown_gnaw":           "res://assets/ui/skills/ICO_SKILL_EnemyCrownGnaw.png",
	"skill:enemy_grave_bell_peal":      "res://assets/ui/skills/ICO_SKILL_EnemyChronoResonance.png",
	"skill:enemy_crystal_sting":        "res://assets/ui/skills/ICO_SKILL_EnemyCrystalRain.png",
	"skill:enemy_skullface_reap":       "res://assets/ui/skills/ICO_SKILL_EnemyClawGuillotine.png",
	"skill:enemy_crystal_burst":           "res://assets/ui/skills/ICO_SKILL_EnemyCrystalBurst.png",
	"skill:enemy_crystal_rain":           "res://assets/ui/skills/ICO_SKILL_EnemyCrystalRain.png",
	"skill:enemy_eldion_crevasse":           "res://assets/ui/skills/ICO_SKILL_EnemyEldionCrevasse.png",
	"skill:enemy_albark_mapless_charge":     "res://assets/ui/skills/ICO_SKILL_EnemyEldionCrevasse.png",
	"skill:enemy_albark_white_silence":      "res://assets/ui/skills/ICO_SKILL_EnemyEldionGlacialBreath.png",
	"skill:enemy_eldion_glacial_breath":           "res://assets/ui/skills/ICO_SKILL_EnemyEldionGlacialBreath.png",
	"skill:enemy_forgedormient_furnace_quake": "res://assets/ui/skills/ICO_SKILL_EnemyEldionCrevasse.png",
	"skill:enemy_forgedormient_slag_breath":  "res://assets/ui/skills/ICO_SKILL_EnemyEldionGlacialBreath.png",
	"skill:enemy_granvel_bramble_crush":           "res://assets/ui/skills/ICO_SKILL_EnemyGranvelBrambleCrush.png",
	"skill:enemy_mycolga_root_bind":         "res://assets/ui/skills/ICO_SKILL_EnemyGranvelBrambleCrush.png",
	"skill:enemy_granvel_verdant_wave":           "res://assets/ui/skills/ICO_SKILL_EnemyGranvelVerdantWave.png",
	"skill:enemy_mycolga_spore_field":       "res://assets/ui/skills/ICO_SKILL_EnemyGranvelVerdantWave.png",
	"skill:enemy_greios_scale_storm":           "res://assets/ui/skills/ICO_SKILL_EnemyGreiosScaleStorm.png",
	"skill:enemy_ink_veil":           "res://assets/ui/skills/ICO_SKILL_EnemyInkVeil.png",
	"skill:enemy_memory_howl":           "res://assets/ui/skills/ICO_SKILL_EnemyMemoryHowl.png",
	"skill:enemy_mist_breath":           "res://assets/ui/skills/ICO_SKILL_EnemyMistBreath.png",
	"skill:enemy_dust_flutter":          "res://assets/ui/skills/ICO_SKILL_EnemyMistBreath.png",
	"skill:enemy_moldgar_abyss_surge":           "res://assets/ui/skills/ICO_SKILL_EnemyMoldgarAbyssSurge.png",
	"skill:enemy_karna_ash_veil":            "res://assets/ui/skills/ICO_SKILL_EnemyMoldgarAbyssSurge.png",
	"skill:enemy_moldgar_mire_maw":           "res://assets/ui/skills/ICO_SKILL_EnemyMoldgarMireMaw.png",
	"skill:enemy_karna_magma_lance":         "res://assets/ui/skills/ICO_SKILL_EnemyMoldgarMireMaw.png",
	"skill:enemy_nereion_breach":           "res://assets/ui/skills/ICO_SKILL_EnemyNereionBreach.png",
	"skill:enemy_nereion_depths_tide_pull":  "res://assets/ui/skills/ICO_SKILL_EnemyNereionBreach.png",
	"skill:enemy_nereion_tidal_wail":           "res://assets/ui/skills/ICO_SKILL_EnemyNereionTidalWail.png",
	"skill:enemy_nereion_depths_abyss_roar": "res://assets/ui/skills/ICO_SKILL_EnemyNereionTidalWail.png",
	"skill:enemy_rune_carapace":           "res://assets/ui/skills/ICO_SKILL_EnemyRuneCarapace.png",
	"skill:enemy_shrapnel_slam":           "res://assets/ui/skills/ICO_SKILL_EnemyClawGuillotine.png",
	"skill:enemy_skarpedion_carapace_ram": "res://assets/ui/skills/ICO_SKILL_EnemyGranvelBrambleCrush.png",
	"skill:enemy_skarpedion_iron_molt":    "res://assets/ui/skills/ICO_SKILL_EnemyRuneCarapace.png",
	"skill:enemy_serdion_roar":           "res://assets/ui/skills/ICO_SKILL_EnemySerdionRoar.png",
	"skill:enemy_valgard_boundary_spear":  "res://assets/ui/skills/ICO_SKILL_EnemySerdionRoar.png",
	"skill:enemy_valgard_rampart":         "res://assets/ui/skills/ICO_SKILL_BossEnrage.png",
	"skill:enemy_sweep_front":           "res://assets/ui/skills/ICO_SKILL_EnemySweepFront.png",
	"skill:enemy_tide_spear":           "res://assets/ui/skills/ICO_SKILL_EnemyTideSpear.png",
	"skill:entangle":           "res://assets/ui/skills/ICO_SKILL_Entangle.png",
	"skill:fear_chain":           "res://assets/ui/skills/ICO_SKILL_FearChain.png",
	"skill:fierce_slash":           "res://assets/ui/skills/ICO_SKILL_FierceSlash.png",
	"skill:focus_mark":           "res://assets/ui/skills/ICO_SKILL_FocusMark.png",
	"skill:frail_dust":           "res://assets/ui/skills/ICO_SKILL_FrailDust.png",
	"skill:grand_elixir":           "res://assets/ui/skills/ICO_SKILL_GrandElixir.png",
	"skill:guard_strike":           "res://assets/ui/skills/ICO_SKILL_GuardStrike.png",
	"skill:hamstring_slash":           "res://assets/ui/skills/ICO_SKILL_HamstringSlash.png",
	"skill:heavy_guard":           "res://assets/ui/skills/ICO_SKILL_HeavyGuard.png",
	"skill:herd_call":           "res://assets/ui/skills/ICO_SKILL_HerdCall.png",
	"skill:hex_bolt":           "res://assets/ui/skills/ICO_SKILL_HexBolt.png",
	"skill:hunter_mark":           "res://assets/ui/skills/ICO_SKILL_HunterMark.png",
	"skill:iron_guard":           "res://assets/ui/skills/ICO_SKILL_IronGuard.png",
	"skill:kindling_strike":           "res://assets/ui/skills/ICO_SKILL_KindlingStrike.png",
	"skill:mark_pursuit":           "res://assets/ui/skills/ICO_SKILL_MarkPursuit.png",
	"skill:menace_strike":           "res://assets/ui/skills/ICO_SKILL_MenaceStrike.png",
	"skill:mend":           "res://assets/ui/skills/ICO_SKILL_Mend.png",
	"skill:ouga_retsudan":           "res://assets/ui/skills/ICO_SKILL_OugaRetsudan.png",
	"skill:pierce_line":           "res://assets/ui/skills/ICO_SKILL_PierceLine.png",
	"skill:plague_bolt":           "res://assets/ui/skills/ICO_SKILL_PlagueBolt.png",
	"skill:power_shot":           "res://assets/ui/skills/ICO_SKILL_PowerShot.png",
	"skill:quick_shot":           "res://assets/ui/skills/ICO_SKILL_QuickShot.png",
	"skill:rend_slash":           "res://assets/ui/skills/ICO_SKILL_RendSlash.png",
	"skill:rime_touch":           "res://assets/ui/skills/ICO_SKILL_RimeTouch.png",
	"skill:salve_burst":           "res://assets/ui/skills/ICO_SKILL_SalveBurst.png",
	"skill:sanctal_strike":           "res://assets/ui/skills/ICO_SKILL_SanctalStrike.png",
	"skill:shield_ram":           "res://assets/ui/skills/ICO_SKILL_ShieldRam.png",
	"skill:slash_attack":           "res://assets/ui/skills/ICO_SKILL_SlashAttack.png",
	"skill:snare_shot":           "res://assets/ui/skills/ICO_SKILL_SnareShot.png",
	"skill:static_strike":           "res://assets/ui/skills/ICO_SKILL_StaticStrike.png",
	"skill:stunning_blow":           "res://assets/ui/skills/ICO_SKILL_StunningBlow.png",
	"skill:swift_slash":           "res://assets/ui/skills/ICO_SKILL_SwiftSlash.png",
	"skill:titan_roar":           "res://assets/ui/skills/ICO_SKILL_TitanRoar.png",
	"skill:toxin_dart":           "res://assets/ui/skills/ICO_SKILL_ToxinDart.png",
	"skill:ultimate_strike":           "res://assets/ui/skills/ICO_SKILL_UltimateStrike.png",
	"skill:umbral_strike":           "res://assets/ui/skills/ICO_SKILL_UmbralStrike.png",
	"skill:venom_burst":           "res://assets/ui/skills/ICO_SKILL_VenomBurst.png",
	"skill:vital_shot":           "res://assets/ui/skills/ICO_SKILL_VitalShot.png",
	"skill:vulnerable_surge":           "res://assets/ui/skills/ICO_SKILL_VulnerableSurge.png",
	"status:poison":                "res://assets/ui/status/ICO_STA_Poison.png",
	"status:chill":                 "res://assets/ui/status/ICO_STA_Chill.png",
	"status:shock":                 "res://assets/ui/status/ICO_STA_Shock.png",
	"status:ignite":              "res://assets/ui/status/ICO_STA_Ignite.png",
	"status:curse":               "res://assets/ui/status/ICO_STA_Curse.png",
	"status:stun":                  "res://assets/ui/status/ICO_STA_Stun.png",
	"status:fear":                  "res://assets/ui/status/ICO_STA_Fear.png",
	"status:vulnerable":          "res://assets/ui/status/ICO_STA_Vulnerable.png",
	"status:armor_break":           "res://assets/ui/status/ICO_STA_ArmorBreak.png",
	"status:mark":                  "res://assets/ui/status/ICO_STA_Mark.png",
	"status:empower":               "res://assets/ui/status/ICO_STA_Empower.png",
	"status:empower_minor":         "res://assets/ui/status/ICO_STA_Empower.png",
	"status:guard":                 "res://assets/ui/status/ICO_STA_Guard.png",
	"status:bleed":                 "res://assets/ui/status/ICO_STA_Bleed.png",
	"status:slow":                  "res://assets/ui/status/ICO_STA_Slow.png",
	"status:enrage":                "res://assets/ui/status/ICO_STA_Enrage.png",
	# 図鑑カテゴリ（歴史・記録・手引き）
	"history:HE-001":           "res://assets/ui/codex/ICO_CDX_HIS_HE001.png",
	"history:HE-002":           "res://assets/ui/codex/ICO_CDX_HIS_HE002.png",
	"history:HE-003":           "res://assets/ui/codex/ICO_CDX_HIS_HE003.png",
	"history:HE-004":           "res://assets/ui/codex/ICO_CDX_HIS_HE004.png",
	"history:HE-005":           "res://assets/ui/codex/ICO_CDX_HIS_HE005.png",
	"history:HE-006":           "res://assets/ui/codex/ICO_CDX_HIS_HE006.png",
	"history:HE-007":           "res://assets/ui/codex/ICO_CDX_HIS_HE007.png",
	"history:HE-008":           "res://assets/ui/codex/ICO_CDX_HIS_HE008.png",
	"history:HE-009":           "res://assets/ui/codex/ICO_CDX_HIS_HE009.png",
	"lore:ancient_record":           "res://assets/ui/codex/ICO_CDX_LF_AncientRecord.png",
	"lore:mourngate_rune_shell":           "res://assets/ui/codex/ICO_CDX_LF_MourngateRuneShell.png",
	"lore:mourngate_pilgrim_marker":           "res://assets/ui/codex/ICO_CDX_LF_MourngatePilgrimMarker.png",
	"lore:mourngate_record_margin":           "res://assets/ui/codex/ICO_CDX_LF_MourngateRecordMargin.png",
	"lore:mourngate_forge_brand":           "res://assets/ui/codex/ICO_CDX_LF_MourngateForgeBrand.png",
	"lore:mourngate_lamp_relief":           "res://assets/ui/codex/ICO_CDX_LF_MourngateLampRelief.png",
	"lore:whisperwood_warden_carving":           "res://assets/ui/codex/ICO_CDX_LF_WhisperwoodWardenCarving.png",
	"lore:whisperwood_canopy_whisper":           "res://assets/ui/codex/ICO_CDX_LF_WhisperwoodCanopyWhisper.png",
	"lore:mistfen_libris_seal":           "res://assets/ui/codex/ICO_CDX_LF_MistfenLibrisSeal.png",
	"lore:mistfen_drowned_ledger":           "res://assets/ui/codex/ICO_CDX_LF_MistfenDrownedLedger.png",
	"currency:arcane_crystal":     "res://assets/ui/batch2/ICO_Currency_Arcanite.png",
	"ticket:ticket_gacha_free":    "res://assets/ui/tickets/ICO_Ticket_GachaFree.png",
	"ticket:ticket_lb_star3":      "res://assets/ui/tickets/ICO_Ticket_LimitBreakStar3.png",
	"ticket:ticket_lb_star4":      "res://assets/ui/tickets/ICO_Ticket_LimitBreakStar4.png",
	# 下ナビ専用（64x64・余白統一）
	"nav:home":                    "res://assets/ui/nav/ICO_NAV_Home.png",
	"nav:adventure":               "res://assets/ui/nav/ICO_NAV_Adventure.png",
	"nav:character":               "res://assets/ui/nav/ICO_NAV_Character.png",
	"nav:party":                   "res://assets/ui/nav/ICO_NAV_Party.png",
	"nav:forge":                   "res://assets/ui/nav/ICO_NAV_Forge.png",
	"nav:equipment":               "res://assets/ui/nav/ICO_NAV_Equipment.png",
	"nav:gacha":                   "res://assets/ui/nav/ICO_NAV_Gacha.png",
	"nav:codex":                   "res://assets/ui/nav/ICO_NAV_Codex.png",
	"nav:settings":                "res://assets/ui/nav/ICO_NAV_Settings.png",
	"nav:mypage":                  "res://assets/ui/nav/ICO_NAV_MyPage.png",
	# UI メニュー / 左サイド（003_01 モック準拠）
	"ui:adventure":                "res://assets/ui/nav/ICO_NAV_Adventure.png",
	"ui:hero":                     "res://assets/ui/menu/ICO_UI_Hero.png",
	"ui:blacksmith":               "res://assets/ui/menu/ICO_UI_Blacksmith.png",
	"ui:roster":                   "res://assets/ui/menu/ICO_UI_Roster.png",
	"ui:codex":                    "res://assets/ui/nav/ICO_NAV_Codex.png",
	"ui:gacha":                    "res://assets/ui/nav/ICO_NAV_Gacha.png",
	"ui:merchant":                 "res://assets/ui/menu/ICO_UI_Merchant.png",
	"ui:gold":                     "res://assets/ui/menu/ICO_UI_Gold.png",
	"ui:exp":                      "res://assets/ui/result/ICO_Result_Exp.png",
	"ui:legacy":                   "res://assets/ui/menu/ICO_UI_Legacy.png",
	"ui:settings":                 "res://assets/ui/nav/ICO_NAV_Settings.png",
	"ui:menu":                     "res://assets/ui/menu/ICO_UI_Menu.png",
	"ui:home":                     "res://assets/ui/nav/ICO_NAV_Home.png",
	"ui:party":                    "res://assets/ui/nav/ICO_NAV_Party.png",
	"ui:dungeon":                  "res://assets/dungeon/mourngate/ICO_DG_Mourngate.png",
	"ui:arena":                    "res://assets/ui/menu/ICO_UI_Arena.png",
	"ui:guild":                    "res://assets/ui/menu/ICO_UI_Guild.png",
	"ui:survey":                   "res://assets/ui/menu/ICO_UI_Survey.png",
	"ui:missions":                 "res://assets/ui/menu/ICO_UI_Missions.png",
	"survey:materials":            "res://assets/ui/survey/ICO_Survey_Materials.png",
	"survey:clue":                 "res://assets/ui/survey/ICO_Survey_Clue.png",
	"survey:dungeon_mourngate":    "res://assets/ui/survey/ICO_Survey_DG_Mourngate.png",
	"passive:battle_fervor":       "res://assets/ui/passives/ICO_PASSIVE_BattleFervor.png",
	# 隊長台帳セクション見出し（64x64）
	"commander:overview":          "res://assets/ui/commander/ICO_CMD_Overview.png",
	"commander:gift_box":          "res://assets/ui/commander/ICO_CMD_GiftBox.png",
	"commander:assets":            "res://assets/ui/commander/ICO_CMD_Assets.png",
	"commander:members":           "res://assets/ui/commander/ICO_CMD_Members.png",
	"commander:records":           "res://assets/ui/commander/ICO_CMD_Records.png",
	"commander:titles":            "res://assets/ui/commander/ICO_CMD_Titles.png",
}

static var _bow_display_cache: Dictionary = {}

static func get_icon_texture(id: String, category: String) -> Texture2D:
	if id.is_empty() or category.is_empty():
		return null
	# 弓クロップ済みキャッシュを優先（load / get_image 回避）
	if category == "weapon" and _bow_display_cache.has(id):
		return _bow_display_cache[id] as Texture2D
	var path: String = ICON_MAP.get("%s:%s" % [category, id], "")
	if path.is_empty() and category == "passive":
		path = passive_icon_path(id)
	if path.is_empty() and category == "ticket":
		var ticket: Resource = DataRegistry.get_ticket_data(id)
		if ticket != null:
			path = str(ticket.icon_path)
	if path.is_empty() or not ResourceLoader.exists(path):
		return null
	var tex: Texture2D = load(path) as Texture2D
	if tex == null:
		return null
	# 弓は原画の余白が大きいので、全画面共通で不透明領域へクロップして表示サイズを揃える。
	if category == "weapon":
		return display_texture_for_weapon(id, tex)
	return tex

## 武器表示用テクスチャ（弓は余白クロップ済み）。テスト／鍛冶からも参照可。
static func display_texture_for_weapon(weapon_id: String, tex: Texture2D) -> Texture2D:
	if tex == null or weapon_id.is_empty():
		return tex
	if _bow_display_cache.has(weapon_id):
		return _bow_display_cache[weapon_id] as Texture2D
	var data: Resource = DataRegistry.get_weapon_data(weapon_id)
	if data == null or str(data.weapon_type) != "bow":
		_bow_display_cache[weapon_id] = tex
		return tex
	var cropped: Texture2D = _crop_opaque_region(tex)
	_bow_display_cache[weapon_id] = cropped
	return cropped

static func _crop_opaque_region(tex: Texture2D) -> Texture2D:
	var img: Image = tex.get_image()
	if img == null or img.get_width() <= 0:
		return tex
	var used: Rect2i = img.get_used_rect()
	if used.size.x <= 0 or used.size.y <= 0:
		return tex
	var pad: int = maxi(2, int(round(float(maxi(used.size.x, used.size.y)) * 0.08)))
	var x0: int = maxi(0, used.position.x - pad)
	var y0: int = maxi(0, used.position.y - pad)
	var x1: int = mini(img.get_width(), used.position.x + used.size.x + pad)
	var y1: int = mini(img.get_height(), used.position.y + used.size.y + pad)
	var region := Rect2(x0, y0, x1 - x0, y1 - y0)
	if region.size.x >= float(tex.get_width()) * 0.92 and region.size.y >= float(tex.get_height()) * 0.92:
		return tex
	var atlas := AtlasTexture.new()
	atlas.atlas = tex
	atlas.region = region
	return atlas

static func passive_icon_path(passive_id: String) -> String:
	if passive_id.is_empty():
		return ""
	var key: String = "passive:%s" % passive_id
	if ICON_MAP.has(key):
		return str(ICON_MAP[key])
	return PassiveIconHelper.icon_path(passive_id)

static func get_stage_icon_texture(stage_id: String) -> Texture2D:
	return get_icon_texture(stage_id, "stage")

static func stage_icon_path(stage_id: String) -> String:
	return ICON_MAP.get("stage:%s" % stage_id, "")
