class_name IconPaths
extends RefCounted

const ICON_MAP: Dictionary = {
	"chr:swordsman":               "res://assets/ui/chr_icons/ICO_CHR_Swordsman.png",
	"chr:ranger":                  "res://assets/ui/chr_icons/ICO_CHR_Ranger.png",
	"chr:alchemist":               "res://assets/ui/chr_icons/ICO_CHR_Alchemist.png",
	"chr:vanguard":                "res://assets/ui/chr_icons/ICO_CHR_Vanguard.png",
	"chr:beast_tamer":             "res://assets/ui/chr_icons/ICO_CHR_BeastTamer.png",
	"weapon:iron_sword":           "res://assets/ui/batch2/ICO_WPN_IronSword.png",
	"weapon:rusted_blade":         "res://assets/ui/batch2/ICO_WPN_RustedBlade.png",
	"weapon:heater_blade":         "res://assets/ui/batch2/ICO_WPN_HeaterBlade.png",
	"weapon:frost_blade":          "res://assets/ui/batch2/ICO_WPN_FrostBlade.png",
	"weapon:bolt_knife":           "res://assets/ui/batch2/ICO_WPN_BoltKnife.png",
	"weapon:apprentice_staff":     "res://assets/ui/batch2/ICO_WPN_ApprenticeStaff.png",
	"weapon:hunting_bow":          "res://assets/ui/batch2/ICO_WPN_HuntingBow.png",
	"weapon:sanctified_dagger":    "res://assets/ui/batch2/ICO_WPN_SanctifiedDagger.png",
	"weapon:ember_fang":           "res://assets/ui/batch2/ICO_WPN_HeaterBlade.png",
	"weapon:glacier_staff":        "res://assets/ui/batch2/ICO_WPN_FrostBlade.png",
	"weapon:storm_edge":           "res://assets/ui/batch2/ICO_WPN_BoltKnife.png",
	"weapon:umbral_fang":          "res://assets/ui/batch2/ICO_WPN_ApprenticeStaff.png",
	"weapon:consecrated_maul":     "res://assets/ui/batch2/ICO_WPN_SanctifiedDagger.png",
	"weapon:unidentified":         "res://assets/ui/batch2/ICO_WPN_Unidentified.png",
	# ② ウィスパーウッド武器（暫定: 既存アイコン流用・オーナー作画待ち / P3-D154）
	"weapon:verdant_cleaver":      "res://assets/ui/batch2/ICO_WPN_IronSword.png",
	"weapon:bark_render":          "res://assets/ui/batch2/ICO_WPN_BoltKnife.png",
	"weapon:verdia_longbow":       "res://assets/ui/batch2/ICO_WPN_HuntingBow.png",
	"weapon:moss_staff":           "res://assets/ui/batch2/ICO_WPN_ApprenticeStaff.png",
	"weapon:pyre_greatsword":      "res://assets/ui/batch2/ICO_WPN_HeaterBlade.png",
	"weapon:tinder_bow":           "res://assets/ui/batch2/ICO_WPN_HuntingBow.png",
	"weapon:willow_ember_staff":   "res://assets/ui/batch2/ICO_WPN_ApprenticeStaff.png",
	"weapon:venom_fang_blades":    "res://assets/ui/batch2/ICO_WPN_BoltKnife.png",
	"weapon:symbiont_edge":        "res://assets/ui/batch2/ICO_WPN_HeaterBlade.png",
	"weapon:mist_piercer":         "res://assets/ui/batch2/ICO_WPN_HuntingBow.png",
	"weapon:silvaria_oathblade":   "res://assets/ui/batch2/ICO_WPN_SanctifiedDagger.png",
	"weapon:veld_branch_staff":    "res://assets/ui/batch2/ICO_WPN_FrostBlade.png",
	# ③ ミストフェン武器（暫定: 既存アイコン流用・オーナー作画待ち / P3-BETA-002）
	"weapon:bog_cleaver":          "res://assets/ui/batch2/ICO_WPN_IronSword.png",
	"weapon:leech_fang_blades":    "res://assets/ui/batch2/ICO_WPN_BoltKnife.png",
	"weapon:mire_longbow":         "res://assets/ui/batch2/ICO_WPN_HuntingBow.png",
	"weapon:driftwood_staff":      "res://assets/ui/batch2/ICO_WPN_ApprenticeStaff.png",
	"weapon:storm_carver":         "res://assets/ui/batch2/ICO_WPN_HeaterBlade.png",
	"weapon:galvanic_bow":         "res://assets/ui/batch2/ICO_WPN_HuntingBow.png",
	"weapon:fen_lantern_staff":    "res://assets/ui/batch2/ICO_WPN_ApprenticeStaff.png",
	"weapon:carapace_saw":         "res://assets/ui/batch2/ICO_WPN_BoltKnife.png",
	"weapon:thunderfen_edge":      "res://assets/ui/batch2/ICO_WPN_HeaterBlade.png",
	"weapon:volt_needle":          "res://assets/ui/batch2/ICO_WPN_HuntingBow.png",
	"weapon:volgrave_thunderblade": "res://assets/ui/batch2/ICO_WPN_SanctifiedDagger.png",
	"weapon:seradion_storm_staff": "res://assets/ui/batch2/ICO_WPN_FrostBlade.png",
	# ④ ブラックショア武器（暫定流用 / P3-BETA-003）
	"weapon:black_sand_cleaver":   "res://assets/ui/batch2/ICO_WPN_IronSword.png",
	"weapon:wreck_hook_blades":    "res://assets/ui/batch2/ICO_WPN_BoltKnife.png",
	"weapon:tidewood_longbow":     "res://assets/ui/batch2/ICO_WPN_HuntingBow.png",
	"weapon:brine_lantern_staff":  "res://assets/ui/batch2/ICO_WPN_ApprenticeStaff.png",
	"weapon:lighthouse_greatsword": "res://assets/ui/batch2/ICO_WPN_HeaterBlade.png",
	"weapon:pharos_bow":           "res://assets/ui/batch2/ICO_WPN_HuntingBow.png",
	"weapon:votive_staff":         "res://assets/ui/batch2/ICO_WPN_ApprenticeStaff.png",
	"weapon:barnacle_saw":         "res://assets/ui/batch2/ICO_WPN_BoltKnife.png",
	"weapon:sanctum_tide_edge":    "res://assets/ui/batch2/ICO_WPN_HeaterBlade.png",
	"weapon:beacon_needle":        "res://assets/ui/batch2/ICO_WPN_HuntingBow.png",
	"weapon:nereidas_tideblade":   "res://assets/ui/batch2/ICO_WPN_SanctifiedDagger.png",
	"weapon:pharoslight_staff":    "res://assets/ui/batch2/ICO_WPN_FrostBlade.png",
	# ⑤ フロストリッジ武器（暫定流用 / P3-BETA-004）
	"weapon:ridge_cleaver":        "res://assets/ui/batch2/ICO_WPN_IronSword.png",
	"weapon:frostclaw_blades":     "res://assets/ui/batch2/ICO_WPN_BoltKnife.png",
	"weapon:snowline_longbow":     "res://assets/ui/batch2/ICO_WPN_HuntingBow.png",
	"weapon:cairn_staff":          "res://assets/ui/batch2/ICO_WPN_ApprenticeStaff.png",
	"weapon:glacier_greatsword":   "res://assets/ui/batch2/ICO_WPN_FrostBlade.png",
	"weapon:rime_bow":             "res://assets/ui/batch2/ICO_WPN_HuntingBow.png",
	"weapon:aurora_staff":         "res://assets/ui/batch2/ICO_WPN_FrostBlade.png",
	"weapon:shadow_fang_saw":      "res://assets/ui/batch2/ICO_WPN_BoltKnife.png",
	"weapon:permafrost_edge":      "res://assets/ui/batch2/ICO_WPN_FrostBlade.png",
	"weapon:white_needle":         "res://assets/ui/batch2/ICO_WPN_HuntingBow.png",
	"weapon:eldion_frostbrand":    "res://assets/ui/batch2/ICO_WPN_SanctifiedDagger.png",
	"weapon:umbra_terminus_staff": "res://assets/ui/batch2/ICO_WPN_ApprenticeStaff.png",
	"armor:leather_armor":         "res://assets/ui/batch2/ICO_ARM_LeatherArmor.png",
	"armor:bone_armor":            "res://assets/ui/batch7/ICO_ARM_BoneArmor.png",
	# ② ウィスパーウッド防具（暫定流用 / P3-D154）
	"armor:moss_weave_garb":       "res://assets/ui/batch2/ICO_ARM_LeatherArmor.png",
	"armor:barkplate_mail":        "res://assets/ui/batch7/ICO_ARM_BoneArmor.png",
	"armor:mycel_cloak":           "res://assets/ui/batch2/ICO_ARM_LeatherArmor.png",
	"armor:wyvern_scale_plate":    "res://assets/ui/batch7/ICO_ARM_BoneArmor.png",
	"armor:warden_vestment":       "res://assets/ui/batch2/ICO_ARM_LeatherArmor.png",
	# ③ ミストフェン防具（暫定流用 / P3-BETA-002）
	"armor:mire_hide_garb":        "res://assets/ui/batch2/ICO_ARM_LeatherArmor.png",
	"armor:chitin_plate":          "res://assets/ui/batch7/ICO_ARM_BoneArmor.png",
	"armor:bog_strider_cloak":     "res://assets/ui/batch2/ICO_ARM_LeatherArmor.png",
	"armor:moldgar_scale_mail":    "res://assets/ui/batch7/ICO_ARM_BoneArmor.png",
	"armor:libris_ward_robe":      "res://assets/ui/batch2/ICO_ARM_LeatherArmor.png",
	# ④ ブラックショア防具（暫定流用 / P3-BETA-003）
	"armor:tidecloth_garb":        "res://assets/ui/batch2/ICO_ARM_LeatherArmor.png",
	"armor:shipplate_mail":        "res://assets/ui/batch7/ICO_ARM_BoneArmor.png",
	"armor:kelp_weave_cloak":      "res://assets/ui/batch2/ICO_ARM_LeatherArmor.png",
	"armor:whalebone_plate":       "res://assets/ui/batch7/ICO_ARM_BoneArmor.png",
	"armor:votive_vestment":       "res://assets/ui/batch2/ICO_ARM_LeatherArmor.png",
	# ⑤ フロストリッジ防具（暫定流用 / P3-BETA-004）
	"armor:furline_garb":          "res://assets/ui/batch2/ICO_ARM_LeatherArmor.png",
	"armor:glacier_plate":         "res://assets/ui/batch7/ICO_ARM_BoneArmor.png",
	"armor:snowdrift_cloak":       "res://assets/ui/batch2/ICO_ARM_LeatherArmor.png",
	"armor:dragon_scale_aegis":    "res://assets/ui/batch7/ICO_ARM_BoneArmor.png",
	"armor:aurora_vestment":       "res://assets/ui/batch2/ICO_ARM_LeatherArmor.png",
	"armor:unidentified":          "res://assets/ui/batch2/ICO_ARM_Unidentified.png",
	"accessory:silver_ring":       "res://assets/ui/batch2/ICO_ACC_SilverRing.png",
	# ② ウィスパーウッド装飾品（暫定流用 / P3-D154）
	"accessory:verdant_ring":      "res://assets/ui/batch2/ICO_ACC_SilverRing.png",
	"accessory:spore_charm":       "res://assets/ui/batch2/ICO_ACC_SilverRing.png",
	"accessory:granvel_fang_talisman": "res://assets/ui/batch2/ICO_ACC_SilverRing.png",
	# ③ ミストフェン装飾品（暫定流用 / P3-BETA-002）
	"accessory:marsh_pearl_ring":  "res://assets/ui/batch2/ICO_ACC_SilverRing.png",
	"accessory:leech_oil_charm":   "res://assets/ui/batch2/ICO_ACC_SilverRing.png",
	"accessory:moldgar_eye_talisman": "res://assets/ui/batch2/ICO_ACC_SilverRing.png",
	# ④ ブラックショア装飾品（暫定流用 / P3-BETA-003）
	"accessory:black_pearl_ring":  "res://assets/ui/batch2/ICO_ACC_SilverRing.png",
	"accessory:barnacle_charm":    "res://assets/ui/batch2/ICO_ACC_SilverRing.png",
	"accessory:nereion_song_talisman": "res://assets/ui/batch2/ICO_ACC_SilverRing.png",
	# ⑤ フロストリッジ装飾品（暫定流用 / P3-BETA-004）
	"accessory:ice_crystal_ring":  "res://assets/ui/batch2/ICO_ACC_SilverRing.png",
	"accessory:frost_fang_charm":  "res://assets/ui/batch2/ICO_ACC_SilverRing.png",
	"accessory:eldion_heart_talisman": "res://assets/ui/batch2/ICO_ACC_SilverRing.png",
	"accessory:unidentified":      "res://assets/ui/batch2/ICO_ACC_Unidentified.png",
	"material:relic_shard":        "res://assets/ui/batch2/ICO_MAT_RelicShard.png",
	"material:elite_relic_shard":  "res://assets/ui/batch7/ICO_MAT_EliteRelicShard.png",
	"material:ancient_bone":       "res://assets/ui/batch7/ICO_MAT_AncientBone.png",
	"material:cursed_iron":        "res://assets/ui/batch7/ICO_MAT_CursedIron.png",
	"material:leather":            "res://assets/ui/batch7/ICO_MAT_Leather.png",
	"enemy:sepia_hound":           "res://assets/codex/enemies/ART_ENM_SepiaHound.png",
	"enemy:rune_roach":            "res://assets/codex/enemies/ART_ENM_RuneRoach.png",
	"enemy:crystal_hedgehog":      "res://assets/codex/enemies/ART_ENM_CrystalHedgehog.png",
	"enemy:crown_eater_rat":       "res://assets/codex/enemies/ART_ENM_CrownEaterRat.png",
	"enemy:clock_moth":            "res://assets/codex/enemies/ART_ENM_ClockMoth.png",
	"enemy:serdion":               "res://assets/codex/enemies/ART_BOSS_Serdion.png",
	"dungeon:mourngate":           "res://assets/dungeon/mourngate/ICO_DG_Mourngate.png",
	"dungeon:whisperwood":         "res://assets/dungeon/whisperwood/ICO_DG_Whisperwood.png",
	"dungeon:mistfen":             "res://assets/dungeon/mistfen/ICO_DG_Mistfen.png",
	"dungeon:broken_marsh":        "res://assets/dungeon/broken_marsh/ICO_DG_BrokenMarsh.png",
	"dungeon:blackshore":          "res://assets/dungeon/blackshore/ICO_DG_Blackshore.png",
	"dungeon:frostridge":          "res://assets/dungeon/frostridge/ICO_DG_Frostridge.png",
	"currency:arcane_crystal":     "res://assets/ui/batch2/ICO_Currency_Arcanite.png",
	# 下ナビ専用（64x64・余白統一）
	"nav:home":                    "res://assets/ui/nav/ICO_NAV_Home.png",
	"nav:adventure":               "res://assets/ui/nav/ICO_NAV_Adventure.png",
	"nav:character":               "res://assets/ui/nav/ICO_NAV_Character.png",
	"nav:party":                   "res://assets/ui/nav/ICO_NAV_Party.png",
	"nav:forge":                   "res://assets/ui/nav/ICO_NAV_Forge.png",
	"nav:gacha":                   "res://assets/ui/nav/ICO_NAV_Gacha.png",
	"nav:codex":                   "res://assets/ui/nav/ICO_NAV_Codex.png",
	"nav:settings":                "res://assets/ui/nav/ICO_NAV_Settings.png",
	# UI メニュー / 左サイド（003_01 モック準拠）
	"ui:adventure":                "res://assets/ui/batch2/ICO_WPN_IronSword.png",
	"ui:hero":                     "res://assets/ui/chr_icons/ICO_CHR_Vanguard.png",
	"ui:blacksmith":               "res://assets/ui/batch7/ICO_CRT.png",
	"ui:roster":                   "res://assets/ui/chr_icons/ICO_CHR_Ranger.png",
	"ui:codex":                    "res://assets/ui/batch7/ICO_MAT_EliteRelicShard.png",
	"ui:gacha":                    "res://assets/ui/batch2/ICO_Currency_Arcanite.png",
	"ui:merchant":                 "res://assets/ui/batch2/ICO_Gold.png",
	"ui:gold":                     "res://assets/ui/batch2/ICO_Gold.png",
	"ui:legacy":                   "res://assets/ui/batch2/ICO_MAT_RelicShard.png",
	"ui:settings":                 "res://assets/ui/batch7/ICO_DEF.png",
	"ui:menu":                     "res://assets/ui/batch7/ICO_ATK.png",
	"ui:home":                     "res://assets/ui/batch2/ICO_MAT_RelicShard.png",
	"ui:party":                    "res://assets/ui/chr_icons/ICO_CHR_Swordsman.png",
	"ui:dungeon":                  "res://assets/dungeon/mourngate/ICO_DG_Mourngate.png",
	"ui:arena":                    "res://assets/ui/batch7/ICO_ATK.png",
	"ui:guild":                    "res://assets/ui/batch7/ICO_DEF.png",
	"ui:missions":                 "res://assets/ui/batch2/ICO_MAT_RelicShard.png",
}

static func get_icon_texture(id: String, category: String) -> Texture2D:
	if id.is_empty() or category.is_empty():
		return null
	var path: String = ICON_MAP.get("%s:%s" % [category, id], "")
	if path.is_empty() or not ResourceLoader.exists(path):
		return null
	return load(path) as Texture2D
